- name: Install the latest version
  tags: vsftpd
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - vsftpd

- name: Copy config
  tags: vsftpd
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: '0666'

- name: Modification the user "sftp"
  tags: vsftpd
  ansible.builtin.user:
    shell: /bin/bash
    name: "{{ sftp_user }}"
    password: "{{ sftp_passwd | password_hash('sha512') }}"
    comment: sftp user
    groups: oleg
    append: true
    state: present
    expires: -1
    password_expire_min: -1
    password_expire_max: -1

- name: Restart service 'vsftpd.service', if running
  tags: vsftpd
  ansible.builtin.systemd:
    name: vsftpd.service
    state: restarted
    enabled: true
  ignore_errors: true
